# Generated by Django 4.2.1 on 2023-05-12 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('manu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodevs.manufacturer')),
            ],
        ),
    ]
