# Generated by Django 4.2.1 on 2023-05-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('R', 'Recycler'), ('M', 'Manufacturer'), ('A', 'Airline')], max_length=1, null=True),
        ),
    ]
