# Generated by Django 4.2.1 on 2023-05-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0002_user_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='title',
            new_name='role',
        ),
    ]
