# Generated by Django 4.2.1 on 2023-05-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0003_alter_product_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='manufacturer',
        ),
    ]
