# Generated by Django 4.2.1 on 2023-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0003_rename_title_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('Landfill_Waste_Saved', models.IntegerField(default=0)),
                ('Energy_Saved', models.IntegerField(default=0)),
                ('New_Parts_Carbon_Footprint', models.IntegerField(default=0)),
                ('Recycled_Parts_Carbon_Footprint', models.IntegerField(default=0)),
                ('Energy_Consumption_New_Parts', models.IntegerField(default=0)),
                ('Renewable_Material_Content', models.FloatField(default=0)),
                ('Carbon_Footprint_Saved', models.IntegerField(default=0)),
                ('Energy_Consumption_Saved', models.IntegerField(default=0)),
                ('Remanufacturing_Potential', models.FloatField(default=0)),
                ('is_Sold', models.BooleanField(default=False)),
            ],
        ),
    ]
