# Generated by Django 4.2.1 on 2023-05-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Percentage_recycled',
            field=models.FloatField(default=0.0),
        ),
    ]
