# Generated by Django 4.2.1 on 2023-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_id',
            field=models.BooleanField(default=False),
        ),
    ]
