# Generated by Django 4.2.1 on 2023-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0004_alter_product_manufacturer_delete_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Energy_Saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Landfill_Waste_Saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Remanufacturing_Potential',
            field=models.FloatField(default=0.0),
        ),
    ]
