# Generated by Django 4.2.1 on 2023-05-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0005_product_energy_saved_product_landfill_waste_saved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Energy_Saved',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Landfill_Waste_Saved',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Remanufacturing_Potential',
        ),
    ]
