# Generated by Django 4.2.1 on 2023-05-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0005_product_percentage_recycled'),
        ('aerodevs', '0007_remove_product_id_alter_product_part_id'),
    ]

    operations = [
    ]
