# Generated by Django 4.2.1 on 2023-05-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodevs', '0007_product_energy_saved_product_landfill_waste_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Carbon_Footprint_Saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Energy_Consumption_New_Parts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Energy_Consumption_Saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='New_Parts_Carbon_Footprint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Recycled_Parts_Carbon_Footprint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Renewable_Material_Content',
            field=models.FloatField(default=0),
        ),
    ]
